In [1]:
import tensorflow as tf
print(tf.reduce_sum(tf.random.normal([1000, 1000])))

tf.Tensor(-2691.5884, shape=(), dtype=float32)


In [2]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:
!nvidia-smi

Mon Dec 23 02:54:07 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.03                 Driver Version: 566.03         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  |   00000000:01:00.0  On |                  Off |
|  0%   42C    P8             27W /  450W |   23610MiB /  24564MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent = ["the glass of milk",
        "the glass of juice",
        "the cup of tea",
        "your videos are good"]

In [10]:
voc_size = 10000

In [11]:
one_hot_rep=[one_hot(words,voc_size) for words in sent]
one_hot_rep

[[9189, 6685, 1457, 758],
 [9189, 6685, 1457, 276],
 [9189, 3867, 1457, 1455],
 [2165, 8639, 3350, 4990]]

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [16]:
max_sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding="pre", maxlen=max_sent_length)
embedded_docs

array([[   0,    0,    0,    0, 9189, 6685, 1457,  758],
       [   0,    0,    0,    0, 9189, 6685, 1457,  276],
       [   0,    0,    0,    0, 9189, 3867, 1457, 1455],
       [   0,    0,    0,    0, 2165, 8639, 3350, 4990]])

In [17]:
## feature representation
## initializing 10 features for each words
dim = 10

In [18]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=max_sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 84ms/step


array([[[-4.9403585e-02, -3.2532960e-05,  4.8411004e-03, -4.5076385e-03,
          4.5721773e-02,  1.4659081e-02,  4.7269035e-02,  2.4916138e-02,
         -7.4906275e-04,  3.3222269e-02],
        [-4.9403585e-02, -3.2532960e-05,  4.8411004e-03, -4.5076385e-03,
          4.5721773e-02,  1.4659081e-02,  4.7269035e-02,  2.4916138e-02,
         -7.4906275e-04,  3.3222269e-02],
        [-4.9403585e-02, -3.2532960e-05,  4.8411004e-03, -4.5076385e-03,
          4.5721773e-02,  1.4659081e-02,  4.7269035e-02,  2.4916138e-02,
         -7.4906275e-04,  3.3222269e-02],
        [-4.9403585e-02, -3.2532960e-05,  4.8411004e-03, -4.5076385e-03,
          4.5721773e-02,  1.4659081e-02,  4.7269035e-02,  2.4916138e-02,
         -7.4906275e-04,  3.3222269e-02],
        [ 1.5033964e-02, -9.9130496e-03,  4.2521823e-02,  3.2550205e-02,
         -3.8831413e-02, -1.5732132e-02,  9.7914934e-03, -2.1204328e-02,
         -4.7597315e-02,  6.2309131e-03],
        [-1.6256429e-02,  3.9760474e-02, -3.5141818e-03, -3.

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 9189, 6685, 1457,  758])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 18ms/step


array([[-4.9403585e-02, -3.2532960e-05,  4.8411004e-03, -4.5076385e-03,
         4.5721773e-02,  1.4659081e-02,  4.7269035e-02,  2.4916138e-02,
        -7.4906275e-04,  3.3222269e-02],
       [-4.9403585e-02, -3.2532960e-05,  4.8411004e-03, -4.5076385e-03,
         4.5721773e-02,  1.4659081e-02,  4.7269035e-02,  2.4916138e-02,
        -7.4906275e-04,  3.3222269e-02],
       [-4.9403585e-02, -3.2532960e-05,  4.8411004e-03, -4.5076385e-03,
         4.5721773e-02,  1.4659081e-02,  4.7269035e-02,  2.4916138e-02,
        -7.4906275e-04,  3.3222269e-02],
       [-4.9403585e-02, -3.2532960e-05,  4.8411004e-03, -4.5076385e-03,
         4.5721773e-02,  1.4659081e-02,  4.7269035e-02,  2.4916138e-02,
        -7.4906275e-04,  3.3222269e-02],
       [ 1.5033964e-02, -9.9130496e-03,  4.2521823e-02,  3.2550205e-02,
        -3.8831413e-02, -1.5732132e-02,  9.7914934e-03, -2.1204328e-02,
        -4.7597315e-02,  6.2309131e-03],
       [-1.6256429e-02,  3.9760474e-02, -3.5141818e-03, -3.9246988e-02,
   